name: Generate and Commit Stubs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-stubs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install mypy

      - name: Generate stub files
        run: |
          make stubs
      - name: Fix Pyi Files
        run: |
          python -m scripts.main fix-pyi-defaults .

      - name: Fix type aliases in stubs
        run: |
          python -m scripts.main fix-types-pyi-aliases ./hexcore/types.pyi ./hexcore/types.py

      - name: Commit and push stubs if changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add '**/*.pyi'
          if ! git diff --cached --quiet; then
            git commit -m "ci: update stub files [skip ci]"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload stubs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: stubs
          path: '**/*.pyi'
